### ISSUE TITLE
Problems with openapi_client

### ISSUE THREAD

**Issue by gregorymurad** [arduino/iot-client-py#40]
Hi,

I have an Arduino API properly set, I am able to get my access token correctly, but when I try to call method **thingsV2List**, for example, I can't seem to import **openapi_client**. I have installed **arduino-iot-client** and **requests-oauthlib** already.

Could you please help me figure out this issue?

Thank you.

Best,

Greg

**Comment by luigigubello** [comment]
Hi @gregorymurad 

Generate an Oauth Token using your API *client_id* and *secret_id*, then try this code and give me a feedback

```
import iot_api_client as iot
from iot_api_client.rest import ApiException
from iot_api_client.configuration import Configuration

from pprint import pprint

client_config = Configuration(host="http://api2.arduino.cc/iot")
client_config.access_token = "YOUR_OAUTH_TOKEN"
client = iot.ApiClient(client_config)

# create an instance of the API class
api_instance = iot.ThingsV2Api(client)

try:
    # list things_v2
    api_response = api_instance.things_v2_list()
    pprint(api_response)
except ApiException as e:
    print("Exception when calling ThingsV2Api->thingsV2List: %s\n" % e)
```

**Comment by gregorymurad** [comment]
Hi @luigigubello,

Thank you very much. It worked just fine. I recently purchased a MKR ENV shield and I am trying to get the data and display using Streamlit.

Have a great one!

Best,

Greg
