### ISSUE TITLE
Arduino IoT Cloud Documentation is completely wrong.

### ISSUE THREAD

**Issue by herzphi** [arduino/iot-client-py#57]
There is a paid subscription model for using the API, but then at least the documentation should be correct (All of the python examples do not work.). Also not all methods listed in the documentation are given in the module.
Example:
- series_v2_historicdata does not exist.
- devices_v2_timeseries cannot be called, because last_evaluated_key is always None. Why is there no explanation, for critical variables?
There should be a way to query historic data, but there is not. Please fix it, it is a paid service.

**Comment by eclipse1985** [comment]
Thanks for the report. We are on it.

**Comment by eclipse1985** [comment]
@herzphi we just released a [new version](https://pypi.org/project/arduino-iot-client/), can you give it a try and let us know?

**Comment by herzphi** [comment]
@eclipse1985 Yes, I can access timeseries data. Thanks for your efforts!
